- name: Samples
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
    - name: Create file
      file:
        path: /tmp/test
        state: touch
        mode: "0644"
